trigger:
  branches:
    include:
      - main

variables:
  dockerHubImageFrontend: sachinthak/frontend
  dockerHubImageBackend: sachinthak/backend

stages:
- stage: BuildAndPush
  displayName: Build and Push to Docker Hub
  jobs:
  - job: DockerBuildPush
    displayName: Build and Push Images
    pool:
      name: Default  # Self-hosted agent pool

    steps:
    - task: DockerInstaller@0
      displayName: Install Docker

    - task: Docker@2
      displayName: Docker Hub Login
      inputs:
        command: login
        containerRegistry: DockerHubServiceConnection  # Must match exact service connection name

    - task: Docker@2
      displayName: Build and Push Frontend Image
      inputs:
        command: buildAndPush
        repository: $(dockerHubImageFrontend)
        dockerfile: frontend/Dockerfile
        containerRegistry: DockerHubServiceConnection
        tags: |
          latest

    - task: Docker@2
      displayName: Build and Push Backend Image
      inputs:
        command: buildAndPush
        repository: $(dockerHubImageBackend)
        dockerfile: backend/Dockerfile
        containerRegistry: DockerHubServiceConnection
        tags: |
          latest
