trigger:
  branches:
    include:
      - main

variables:
  dockerHubImageFrontend: ravisuryabanshi/frontend
  dockerHubImageBackend: ravisuryabanshi/backend

stages:
- stage: BuildAndPush
  displayName: Build and Push to Docker Hub
  jobs:
  - job: DockerBuildPush
    pool:
      name: Default  # Self-hosted agent pool

    steps:
    - task: DockerInstaller@0
      displayName: Install Docker

    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: 'DockerHubServiceConnection'  # Use the exact service connection name

    - task: Docker@2
      displayName: 'Build and Push Frontend'
      inputs:
        command: buildAndPush
        repository: $(dockerHubImageFrontend)
        dockerfile: frontend/Dockerfile
        containerRegistry: 'DockerHubServiceConnection'
        tags: |
          latest

    - task: Docker@2
      displayName: 'Build and Push Backend'
      inputs:
        command: buildAndPush
        repository: $(dockerHubImageBackend)
        dockerfile: backend/Dockerfile
        containerRegistry: 'DockerHubServiceConnection'
        tags: |
          latest
