trigger:
  branches:
    include:
      - main

variables:
  acrName: hello3tieracr
  acrLoginServer: hello3tieracr.azurecr.io
  frontendImage: frontend
  backendImage: backend

stages:
- stage: BuildAndPush
  displayName: Build and Push to ACR
  jobs:
  - job: DockerBuildPush
    pool:
      name: myself-hosted 
      demands:
        - agent.name -equals yvikrant4600454 

    steps:
    - task: DockerInstaller@0

    - task: Docker@2
      displayName: 'Login to ACR'
      inputs:
        command: login
        containerRegistry: 'hello3tieracr-service-connection'  # Create this in next step

    - task: Docker@2
      displayName: 'Build and push Frontend'
      inputs:
        repository: $(frontendImage)
        dockerfile: frontend/Dockerfile
        containerRegistry: 'hello3tieracr-service-connection'
        command: buildAndPush
        tags: |
          latest

    - task: Docker@2
      displayName: 'Build and push Backend'
      inputs:
        repository: $(backendImage)
        dockerfile: backend/Dockerfile
        containerRegistry: 'hello3tieracr-service-connection'
        command: buildAndPush
        tags: |
          latest

